require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable

Metrics/BlockLength:
  AllowedMethods: ['describe']

Style/Documentation:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false
